### ISSUE TITLE
Error while running cargo after installing

### ISSUE THREAD

**Issue by Souldiv** [robertdebock/ansible-role-cargo#1]
# Describe the bug

Gives error when trying to run cargo after installing using the role

## Playbook

```yaml
---
# Install Cargo
- name: Install cargo
  ansible.builtin.include_role:
    name: robertdebock.cargo
```

## Output

![image](https://github.com/robertdebock/ansible-role-cargo/assets/25404248/55c53956-b470-4bed-828b-bb0ea4f8289c)

## Environment

![image](https://github.com/robertdebock/ansible-role-cargo/assets/25404248/a6ca8ca0-7d5f-4662-9472-7da0eef5fcbc)

I fixed it by simply running `rustup default stable` to install the stable toolchain. Is this intended to run the command manually?
